---

# Site options
title: Sigma theme
baseurl: ""  # Subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000"
lang: en
permalink: /:title/
sticky_menu: true
scrollup: true
topbar: true
footer_icons: true

# Logo path
logo:
  path: /logo/logo.svg
  width: 131
  height: 25

# Favicons
favicon_ico: /favicon.ico
apple_touch: /icons/apple-touch-icon.png
favicon_16: /icons/favicon-16x16.png
favicon_32: /icons/favicon-32x32.png
webmanifest: /icons/site.webmanifest
browserconfig: /icons/browserconfig.xml
mask_icon: /icons/safari-pinned-tab.svg
mask_color: "#f17e01"

# Theme color
theme_color: "#848688"

# Home settings
home:
  header:
    title: Sigma-theme for <span>Jekyll</span> v4.0.0
    text: >-
      This theme is focused on <strong>speed</strong> and <strong>SEO</strong>,
      taking care of a <a href="/">beautiful</a> appearance, with
      <u>golden proportions</u>,
      a responsive design, a sticky menu and a lot of options.

# Breadcrumbs
bc_sep: /

# Open Graph
fb_admins: 123456789012345
fb_app_id: 123456789012345
og_locale: en_US

# Twitter cards
twc_user: jekyllrb

# Social media links
google_analytics: UA-12345678-1
twitter_username: jekyllrb
facebook_username: jekyllrb
github_username: jekyll
rss_feed: https://feeds.feedburner.com/jekyll
sitemap_link: true
color_toggle: true
search_url: /search/

# Web services
# google_sv:
# bing_sv:
# adsense: ca-pub-0123456789012345

# Footer information
first_year: 2019
copyright: Made with love ♥

# Add scripts
latex: false
version: "3.0.0"

# Defaults for all posts and all pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      read_time: true
      breadcrumbs: true
      share: true
      rouge: true
      nextprev: cat
      sidebar: right
      sticky_side: true
      postmeta: true
      ldjson: true
      og_type: article
      sidenav:
        posts: true
  - scope:
      path: ""
      type: "pages"
    values:
      read_time: true
      breadcrumbs: true
      share: false
      sidebar: right
      sticky_side: true
      sidenav:
        pages: true
        categories: true

# Build settings
markdown: kramdown
theme: sigma-theme
plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-sitemap

# include:
#   - .htaccess
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - deploy.sh
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
